### ISSUE TITLE
CSS displays wrong version (v0.2.3)

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/simple-server#33]
After upgrading CSS from 0.2.2 to 0.2.3 my server displays:

> You are running a Simple Chocolatey Package Repository v0.2.2.0

I also get transform errors (related?) which I've previously documented (https://github.com/chocolatey/choco/issues/1482).

chocolatey.server v0.2.3 [Approved]
chocolatey.server package files upgrade completed. Performing other installation steps.
Transforming 'Web.config' with the data from 'Web.config.install.xdt'
**Error transforming config file:
 Data at the root level is invalid. Line 230, position 17.**
Transforming 'Web.config' with the data from 'Web.config.install.xdt'
**Error transforming config file:
 Data at the root level is invalid. Line 230, position 17.**
 ShimGen has successfully created a shim for 7za.exe
 The upgrade of chocolatey.server was successful.
  Software installed to 'C:\tools\chocolatey.server'

Chocolatey upgraded 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**Comment by ferventcoder** [comment]
The website pulls the information directly from the dll, so it means you didn't have a good upgrade. Something went wrong somewhere. So you should move to manually interject to have the upgrade be successful.

Yes you've previously documented the issue for transform errors - it's a known issue and determining the actual cause is what is the most difficult part.

**Comment by bcurran3** [comment]
I had a feeling that the displayed version was pulled from somewhere and my upgrade failed. :(

**Comment by bcurran3** [comment]
Under further investigation I've determined this is a self inflicted wound.
I didn't move the new files from the default installation path to my actual installation path. :)
Now that I've done that, I'm seeing the new information. Looks like you added a lot...I need to go read it.
