### ISSUE TITLE
FEATURE REQUEST: clearly define setting apikey on server and client

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/simple-server#34]
Related to https://github.com/chocolatey/simple-server/issues/25, but didn't achieve (my) desired result.

I think the way information about the apikey setup still leads to a lot of confusion. It needs to be better defined between configuring the server versus the client.

On the local display page for CSS (admin):

Change:

> Please set that using the setapikey command above, substituting that value for '{apikey}'. 

To: "You can change the apikey for this Simple Chocolatey Package Repository by searching for and editing "add key="apiKey" value=" in Web.config found in the chocolatey.server installation folder."

Change (repository urls):

> You can set the ApiKey for this repository with 

to "You can set your choco client to use the ApiKey for this for this Simple Chocolatey Package Repository by issuing the following command:"

----------------------------------

SIDENOTE:

I think it's more logical to display

> You can set the ApiKey for this repository with (or my suggest new terminology above)
> choco setapikey --source="http://myserver/chocolatey" --api-key={apikey} 

before

> Use the command below to push packages to this feed using the Chocolatey command line tool (choco.exe). 
> choco.exe push [{package file}] --source http://myserver/chocolatey [--api-key={apikey}] 

as doing the (my suggested) first negates the need to specify the apikey in the (my suggested) second example

In case you didn't notice, I'm (unofficial QA team here) all about keeping relevant information related to the location of usefulness instead of having to search for documentation. It makes a big difference in the time taken to accomplish installation tasks when FAQ type information is readily present and documentation doesn't need to be referenced. :)

**Comment by ferventcoder** [comment]
I think you probably didn't have a good upgrade.

**Comment by ferventcoder** [comment]
![image](https://user-images.githubusercontent.com/63502/36105949-840fd51c-0fdb-11e8-8e1f-322c6f165d4e.png)

**Comment by ferventcoder** [comment]
![image](https://user-images.githubusercontent.com/63502/36105963-920739ee-0fdb-11e8-8d95-9af34cb9b94b.png)

**Comment by ferventcoder** [comment]
Please confirm this is what you are now seeing? Right now I'm not getting a warm and fuzzy that you are.

**Comment by bcurran3** [comment]
I'm not seeing that. Upgrade gave errors and evidently failed. I have a mention of this in https://github.com/chocolatey/simple-server/issues/33

Let me know what you want to know.

**Comment by ferventcoder** [comment]
I have all I need. You should probably take a look at the logs to see if there is any feedback you can provide on why it failed. Then copy over the new stuff from the chocolatey lib folder. Also check that web.config as well.

**Comment by bcurran3** [comment]
Under further investigation I've determined this is a self inflicted wound.
I didn't move the new files from the default installation path to my actual installation path. :)
Now that I've done that, I'm seeing the new information. Looks like you added a lot...I need to go read it.
