### ISSUE TITLE
FEATURE REQUEST: LAMP compatible version of CSS

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/simple-server#35]
A LAMP ( Linux, Apache, MySQL, PHP) version of CSS would be truly desirable! 

The thought of using CSS on an inexpensive hosted VPS would be a big boon for MSPs/VARs that want to provide more conformity, centralization, ease of use, and control over a custom feed then services such as MyGet provide. MSPs/VARs could use one central source for clients that don't have the resources to host an internal server. (Distribution rights observed.) Could also be used for a tiered trickle down scenario though I don't believe this is built in by design at the moment. If package hand off (https://github.com/chocolatey/simple-server/issues/16) was added and configurable, theoretically packages could be created and tested from one server, pushed out to a private tier 1 repository, then pushed down to tier 2 repositories.

**Comment by ferventcoder** [comment]
It's a good request. There are options available for that now. https://chocolatey.org/docs/how-to-host-feed (look at all known options).

**Comment by ferventcoder** [comment]
Unfortunately Chocolatey Simple Server is not going to head this route, as indicated in the last email there are options for that.
