### ISSUE TITLE
Slow to Respond when cold

### ISSUE THREAD

**Issue by FrankV01** [chocolatey/simple-server#4]
I've deployed this and when the server is cold (no requests) the following command (_example_) takes 45 or more seconds to respond. After that, it runs normally but once the server "sleeps" again (I suppose), it then takes another several second to respond. 

    choco list --source "http://serverName/choco/chocolatey"

The command is an example, any interaction to get packages or make queries into the server when cold is slow or even times out.

**Comment by ferventcoder** [comment]
@FrankV01 I agree for the most part. It would be great if a website could better manage staying warm.

**Comment by ferventcoder** [comment]
We've added documentation at https://chocolatey.org/docs/how-to-set-up-chocolatey-server#additional-configuration, which should address this and more.
