### ISSUE TITLE
install.ps1 - Function Download-Script is called before its definition

### ISSUE THREAD

**Issue by theonlydude1** [chocolatey/simple-server#41]
Hello,
In version 0.2.3 install.ps1 call the function Download-String in line 26 but the function is defined starting line 134 resulting in a commandnotfound error.
Is it possible to move the function definitions at the top of the script ?

**Comment by ferventcoder** [comment]
Good catch, let's make that adjustment.

**Comment by ferventcoder** [comment]
That was a last minute change, definitely need to fix that.

**Comment by ferventcoder** [comment]
This has been pushed with 0.2.4. Look for that when moderation finishes in about 1-2 hours.
