### ISSUE TITLE
All packages are unzipped and deleted in packages folder

### ISSUE THREAD

**Issue by robertZaufall** [chocolatey/simple-server#48]
When a client wants to install or upgrade a package sometimes all packages are unzipped and deleted on the server leaving the whole server unfunctional.

**Comment by ferventcoder** [comment]
@robertZaufall just seeing this - what do you mean?

**Comment by robertZaufall** [comment]
I was observing situations when all nupkg files in chocolatey.server\App_Data\Packages were extracted to folders and afterwards deleted, so only these folders containing the nupkg artifacts were remaining.

**Comment by ferventcoder** [comment]
This is mostly normal, it should be pushing those packages down to subfolders and removing the top level nupkg. If you see it not keeping the nupkg in the subfolder (`<package id>\<package version>`), then we can look more into what you are seeing.
