### ISSUE TITLE
Package overview not showing all packages

### ISSUE THREAD

**Issue by jepsa01** [chocolatey/simple-server#57]
When I'm browsing through the package list via https://mychocosrv/chocolatey/Packages the overview does not show all packages. Is this a bug or caching problem? If I'm using 'choco list' all packages from the repository are shown correctly...

Any ideas?

**Comment by peterbarendse** [comment]
It only shows the first 50 packages. 
Try this to see the next 50
`https://yourchocoserver/chocolatey/Packages?$skip=50"`

**Comment by ferventcoder** [comment]
Better not to use that - what you are browsing to is likely making it look nice but it is just XML (Atom feed) and not meant for looking at. Use ChocolateyGUI hooked up to the source if you want a good view of it. HTH
