### ISSUE TITLE
Resource not found for the segment 'packages'.

### ISSUE THREAD

**Issue by Spamme1** [chocolatey/simple-server#7]
This is funny because URLs should be case-insensitive, but this URL with capitalized **P** works:
http://chocosserver:8000/chocolatey/Packages
But with a lower **p** it throws the following error:
```
<error>
  <code/>
  <message xml:lang="en-US">Resource not found for the segment 'packages'.</message>
</error>
```

**Comment by ferventcoder** [comment]
@Spamme1 Once you get into the OData part of the URL, it has different rules. In this case, it requires the capital. You typically wouldn't need to pass that url for "Packages" to anything.

**Comment by ferventcoder** [comment]
Closing as a question.
